spring.application.name=AIChatAPI

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.5-flash
spring.ai.google.genai.chat.temperature=0.5
spring.ai.google.genai.chat.max-output-tokens=2000